# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reference Platforms for the ARM Ecosystem
description: |-
  Linaro Reference Platform is an end to end, open software stack.
  This product aims to showcase the latest available ARM optimizations,
  through validation, on a series of hardware platforms. (189 characters)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://platforms.linaro.org/" # the base hostname & protocol for your site, e.g. http://example.com

using_assets: true

# Build settings
markdown: kramdown
theme: linaro-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-readme-index
# Jekyll Assets plugin - set js and css to true so it compresses on jekyll build
assets:
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  sources:
    - assets/images
    - assets/js
    - assets/css
    
# Sass Configuration.
sass:
    style: compressed
    load_paths:
        - assets/css
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
